name: gcp_dbt_bqdwh
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# flags:
#   warn_error_options:
#     silence:
#       - ConstraintNotEnforced

clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ dbt_external_tables.stage_external_sources() }}"

vars:
  biglake_connection_name: 'us-central1.conn'
